message: "Hello from Git"
some:
  default:
    property: defaultValue
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
