server:
  port: 8084

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8883/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: mysecretkey
  expiration: 3600
