server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UmbertoDiP/ecommerce-config-repo
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud: DEBUG

security:
  user:
    name: configuser
    password: configpassword
