server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UmbertoDiP/ecommerce-config-repo
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
