server:
  port: 8762
spring:
  application:
    name: eurekaserver
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
